[package]
name = "network"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
proto = { path = "../proto" }
reqwest = { version = "0.12.7", features = ["multipart", "gzip"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
