[versions]
kotlin = "2.0.20"
kotlinx-coroutines-bom = "1.9.0"

android-gradle-plugin = "8.6.1"
android-desugar-jdk-libs = "2.1.2"
androidx-core = "1.13.1"
androidx-activity = "1.9.2"
androidx-annotation = "1.8.2"
androidx-compose-bom = "2024.09.02"
androidx-avigation-compose = "2.8.1"

koin-bom = "4.0.0"
coil-bom = "2.7.0"

jna = "5.15.0"
timber = "5.0.1"
kover = "0.8.3"
test-logger = "4.0.0"
spotless = "6.25.0"
ktlint = "1.3.1"

[libraries]
kotlinx-coroutines-bom = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines-bom" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

android-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugar-jdk-libs" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotaion = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-avigation-compose" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }

coil-bom = { module = "io.coil-kt:coil-bom", version.ref = "coil-bom" }
coil = { module = "io.coil-kt:coil" }
coil-compose = { module = "io.coil-kt:coil-compose" }
coil-gif = { module = "io.coil-kt:coil-gif" }
coil-svg = { module = "io.coil-kt:coil-svg" }

jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kover-gradle-plugin = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version.ref = "kover" }
test-logger-gradle-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "test-logger" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }

kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

tiebax-kover = { id = "tiebax.kover" }
tiebax-spotless = { id = "tiebax.spotless" }
tiebax-android-application = { id = "tiebax.android.application" }
tiebax-android-application-compose = { id = "tiebax.android.application.compose" }
tiebax-android-application-kover = { id = "tiebax.android.application.kover" }
tiebax-android-library = { id = "tiebax.android.library" }
tiebax-android-library-compose = { id = "tiebax.android.library.compose" }
tiebax-android-library-kover = { id = "tiebax.android.library.kover" }
