# Project name
name: TiebaX

# Project attributes
attributes:
  BuildIndependentTargetsInParallel: true

# Project options
options:
  localPackagesGroup: ""
  minimumXcodeGenVersion: 2.15
  defaultConfig: Release
  groupSortPosition: top
  generateEmptyDirectories: true
  createIntermediateGroups: true
  transitivelyLinkDependencies: true
  parallelizeBuild: true
  usesTabs: false
  tabWidth: 2
  indentWidth: 2
  deploymentTarget:
    iOS: 16.0

# Project build configurations
configs:
  Debug: debug
  Release: release

# Project base settings
configFiles:
  Debug: App/Sources/Tiebax.xcconfig
  Release: App/Sources/Tiebax.xcconfig

# Scheme templetes
schemeTemplates:
  baseScheme:
    build:
      targets:
        Tiebax: all
    run:
      config: ${configName}
    test:
      config: ${configName}
    profile:
      config: ${configName}
    analyze:
      config: ${configName}
    archive:
      config: ${configName}

# Project schemes
schemes:
  Tiebax - Debug:
    templates:
      - baseScheme
    templateAttributes:
      configName: Debug
    test:
      testPlans:
        - path: App/Tests/UnitTests.xctestplan
          defaultPlan: true

  Tiebax - Release:
    templates:
      - baseScheme
    templateAttributes:
      configName: Release

# Project target shared settings
settingGroups:
  target:
    base:
      CODE_SIGN_STYLE: Manual
      TARGETED_DEVICE_FAMILY: 1
    configs:
      debug:
        DEVELOPMENT_TEAM: none
        CODE_SIGN_IDENTITY: iPhone Developer
      release:
        DEVELOPMENT_TEAM: none
        CODE_SIGN_IDENTITY: iPhone Distribution

# Packages
packages:
  Modules:
    path: ./

# Project targets
targets:
  Tiebax:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - Package.swift
    dependencies:
      - package: Modules
        products:
          - AppFeature
    info:
      path: App/Sources/Info.plist
      properties:
        AppIdentifier: $(APP_IDENTIFIER)
        AppIdentifierPrefix: $(AppIdentifierPrefix)
        CFBundleName: $(APP_NAME)
        CFBundleShortVersionString: $(APP_VERSION)
        CFBundleVersion: $(APP_BUILD_VERSION)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleInfoDictionaryVersion: "6.0"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: ["armv7"]
        UIApplicationSupportsIndirectInputEvents: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
          UISceneConfigurations: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
    settings:
      groups: [target]
      base:
        APP_NAME: TiebaX
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        OTHER_SWIFT_FLAGS: -Xcc -Wno-incomplete-umbrella
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS)
        ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON_NAME)
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_IDENTIFIER)$(APP_IDENTIFIER_SUFFIX)
      configs:
        Debug:
          APP_ICON_NAME: app-icon.debug
          APP_IDENTIFIER_SUFFIX: .debug
        Release:
          APP_ICON_NAME: app-icon
          APP_IDENTIFIER_SUFFIX:
    preBuildScripts:
      - script: make format-swift-files
        name: Run Swift Format
        basedOnDependencyAnalysis: false
    postCompileScripts:
      - script: make lint-swift-files
        name: Run Swift Lint
        basedOnDependencyAnalysis: false
