[build]
target-dir = ".build"

[env]
TIEBA_APK_DOWNLOAD_URL = { value = "https://tieba.baidu.com/mo/q/activityDiversion/download" }
TIEBA_APK_DOWNLOAD_PATH = { value = ".build/tmp/tieba.apk" }
TIEBA_APK_SOURCE_EXPORT_DIR = { value = ".build/tmp/sources/tieba" }
TIEBA_APK_PROTOBUF_GEN_DIR = { value = ".build/tmp/protobuf" }

PROTOBUG_GEN_DIR = { value = ".build/tmp/gen" }

[alias]
apk-download = ["run", "--package", "apk-download"]
apk-protobuf-gen = ["run", "--package", "apk-protobuf-gen"]
protobuf-gen = ["run", "--package", "protobuf-gen"]
