[package]
name = "core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "tiebax_core"

[dependencies]
crypto = { path = "../crypto" }
network = { path = "../network" }
